

POST http://localhost:3000/alunos/add

Content-Type: application/json

{
    "name": "Ryan",
    "cpf": "06593397148",
    "dateOfbirth": "11/05/2003",

}

###

POST http://localhost:3000/cursos/add
Content-Type: application/json

{
    "name": "next.js",
    "description": "gfdgdshf",
    "duration": 180

}

